Repository teemtee/fmf, pull requests merged in 2021-02, with the labels that each got.

#105 Store commit hash if the tree is under a git repo
  fmf/base.py
  tests/unit/test_base.py
Labels: enhancement

#104 Use the origin default branch instead of master
  docs/concept.rst
  fmf/base.py
  fmf/utils.py
  tests/unit/test_utils.py
Labels: fetch

#106 Support calls fetch(destination, env) and run(env)
  fmf/utils.py
  tests/unit/test_utils.py
Labels: fetch, must

#98 Implement a new method copy() for cloning nodes
  fmf/base.py
  tests/unit/test_base.py
Labels: enhancement, tree

#107 Enable integration testing with tmt, some cleanup
  .gitignore
  plans/docs.fmf
  plans/features.fmf
  plans/integration.fmf
  plans/main.fmf
  tests/main.fmf
Labels: tests

#97 Use locking to checkout/read tree
  fmf.spec
  fmf/base.py
  fmf/utils.py
  setup.py
  tests/unit/test_base.py
  tests/unit/test_utils.py
Labels: enhancement

#108 Store command output in run(), fetch() exceptions
  fmf/utils.py
  tests/unit/test_utils.py
Labels: enhancement

#109 Simplify special distro comparison examples
  docs/context.rst
Labels: context, docs
