Repository teemtee/fmf, pull requests merged in 2021-03, with the labels that each got.

#110 Prevent exploring tests in the tmt directory
  Makefile
Labels: packaging

#111 Allow to set desired cache location
  README.rst
  fmf/utils.py
  tests/unit/test_utils.py
Labels: cache

#113 Raise FileException on duplicate YAML keys
  fmf/base.py
  tests/unit/test_base.py
Labels: enhancement

#115 Fetch whole tree using utils.get_remote_tree
  fmf/base.py
  fmf/utils.py
  tests/unit/test_base.py
  tests/unit/test_utils.py
Labels: cache, enhancement, fetch

#118 Functions to manipulate cache
  fmf/utils.py
  tests/unit/test_utils.py
Labels: cache

#119 Release fmf-0.15
  fmf.spec
Labels: packaging

#120 A bunch of adjustments for the epel-7 build
  .packit.yaml
  Makefile
  fmf.spec
  fmf/base.py
  fmf/utils.py
  tests/basic/test.sh
  tests/docs/test.sh
  tests/unit/main.fmf
  tests/unit/test_base.py
  tests/unit/test_cli.py
  tests/unit/test_modify.py
  tests/unit/test_utils.py
Labels: packaging, tests

#121 Do not use mutable objects as default arguments
  fmf/base.py
Labels: base
