Repository teemtee/fmf, pull requests merged in 2022-07, with the labels that each got.

#147 Version as fmf flag and module attribute
  Makefile
  fmf/__init__.py
  fmf/cli.py
  tests/unit/test_cli.py
Labels: base

#176 Enable the flake8 check, fix detected issues
  .pre-commit-config.yaml
  docs/contribute.rst
  fmf/__init__.py
  fmf/base.py
  fmf/utils.py
  tests/unit/test_adjust.py
  tests/unit/test_base.py
  tests/unit/test_context.py
  tests/unit/test_modify.py
  tests/unit/test_utils.py
Labels: style

#175 Select by the source of object
  fmf/base.py
  fmf/cli.py
  tests/unit/data/select_source/.fmf/version
  tests/unit/data/select_source/foo/inner/main.fmf
  tests/unit/data/select_source/foo/special.fmf
  tests/unit/data/select_source/main.fmf
  tests/unit/test_base.py
  tests/unit/test_cli.py
Labels: base

#180 Retry if shallow clone fails
  fmf/utils.py
Labels: utils

#181 Release fmf-1.2.1
  fmf.spec
Labels: packaging
