Repository teemtee/fmf, pull requests merged in 2023-09, with the labels that each got.

#212 Drop support for `el-8` and `python-3.6`
  .packit.yaml
  setup.py
Labels: packaging

#197 Add callback to adjust() to make it observable by callers
  fmf/base.py
  tests/unit/test_adjust.py
Labels: enhancement

#211 Fix missing file require for unit tests
  tests/unit/main.fmf
Labels: tests

#214 Move the copr repository to the `teemtee` group
  .packit.yaml
  README.rst
Labels: packaging

#195 Allow case-insensitive matching of context dimension values
  docs/context.rst
  fmf/base.py
  fmf/context.py
  tests/unit/test_adjust.py
  tests/unit/test_context.py
Labels: context, base
