Repository teemtee/fmf, pull requests merged in 2024-12, with the labels that each got.

#253 Use the `referencing` library where available
  .gitignore
  fmf/_compat/__init__.py
  fmf/_compat/jsonschema.py
  fmf/utils.py
Labels: packaging, utils

#260 Keep order of the operation when merging values
  docs/features.rst
  examples/merge/parent.fmf
  fmf/base.py
  tests/unit/test_base.py
Labels: base

#251 Enable the `epel-10` building and testing
  .packit.yaml
Labels: tests, packaging

#261 Enable downstream jobs, simplify packit config
  .packit.yaml
Labels: packaging

#263 Handle nested `dict` extending non-existent keys
  examples/deep/main.fmf
  fmf/base.py
  tests/unit/test_base.py
Labels: base

#262 Release fmf-1.5.0
  README.rst
  docs/releases.rst
Labels: packaging

#268 Fix the `pipx` command in the `release` action
  .github/workflows/release.yml
Labels: packaging

#269 Sync the `.packit.yaml` config to downstream repo
  .packit.yaml
Labels: packaging
